FROM node:10.16.2-alpine

RUN node -v && npm -v

WORKDIR /app

RUN npm install -g @angular/cli@11.0.1

COPY ./package.json ./

RUN npm install

COPY . .

# RUN ng build
# CMD ["ng", "build", "--watch=true", "--poll=1000"]