FROM node:14.15-alpine

RUN node -v && npm -v

WORKDIR /app

RUN npm install -g @angular/cli@11.0.1 http-server

COPY ./package.json ./

RUN npm install

COPY . .

RUN ng build --configuration testing
