FROM node:10.16.2-alpine as builder

RUN node -v && npm -v

WORKDIR /app

# To handle 'not get uid/gid' in Travis CI. Try to remove this in the future
RUN npm config set unsafe-perm true

RUN npm install -g @angular/cli@11.0.1

COPY ./package.json ./

RUN npm install

# To undo the change made above
RUN npm config set unsafe-perm false

COPY . .

RUN ng build --configuration=testing

# This nginx is just for serving the frontend assets
# the other one in the nginx folder is for routing between the client and the server
FROM nginx

# EBS reads this and creates the mapping when starts the container
EXPOSE 4200

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/client /usr/share/nginx/html

#nginx image has its own entrypoint that by default starts nginx server