FROM node:8-alpine

RUN node -v && npm -v

WORKDIR /app

RUN npm install -g @angular/cli@7.0.3

COPY ./package.json ./

RUN npm install

COPY . .

# RUN ng build
# CMD ["ng", "build", "--watch=true", "--poll=1000"]