version: '3'
services:
  mongo:
    image: mongo:3.6.13-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
    - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}

  acserver:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # ports: 
    #   - "7777:7777"
    environment:
      NODE_ENV: ${ENV}
      DATABASE: ${DATABASE}
      DATABASE_TEST: ${DATABASE_TEST} # required to run data-handler.js against test env
      DATABASE_PROD: ${DATABASE_PROD} # required to run data-handler.js against prod env
      MAIL_TRAP_USER: ${MAIL_TRAP_USER}
      MAIL_TRAP_PASS: ${MAIL_TRAP_PASS}
      MAIL_TRAP_HOST: ${MAIL_TRAP_HOST}
      MAIL_TRAP_PORT: ${MAIL_TRAP_PORT}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      PORT: ${PORT}
      SECRET: ${SECRET}
      KEY: ${KEY}
      CURRENCYLAYER_KEY: ${CURRENCYLAYER_KEY}
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_KEY: ${PUSHER_KEY}
      PUSHER_SECRET: ${PUSHER_SECRET}
      PUSHER_CLUSTER: ${PUSHER_CLUSTER}
    volumes:
    - /app/node_modules
    - ./server:/app
    command: ["npm", "run", "dev"]

  acclient:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    # ports: 
    #   - "4200:4200"
    volumes:
    - /app/node_modules
    - ./client:/app
    command: ["npm", "start"]
  
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
    - "2222:80"
  
  certbot:
    image: certbot/certbot
    volumes:
    - ./nginx/certbot/conf:/etc/letsencrypt
    - ./nginx/certbot/www:/var/www/certbot
