sudo: required
services:
  - docker

after_success:
  - docker build -t maxipaolucci/atomic-coconut-client ./client
  - docker build -t maxipaolucci/atomic-coconut-nginx ./nginx
  - docker build -t maxipaolucci/atomic-coconut-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maxipaolucci/atomic-coconut-client
  - docker push maxipaolucci/atomic-coconut-nginx
  - docker push maxipaolucci/atomic-coconut-server
