sudo: required
services:
  - docker 

before_install:
  - docker build -t $DOCKER_ID/atomic-coconut-client-dev -f ./client/Dockerfile.dev ./client

script:
  # - docker run -e CI=true $DOCKER_ID/atomic-coconut-client npm run test -- --coverage
  - docker run -e CI=true $DOCKER_ID/atomic-coconut-client-dev ng build

after_success:
  - docker build -t $DOCKER_ID/atomic-coconut-client ./client
  - docker build -t $DOCKER_ID/atomic-coconut-nginx ./nginx
  - docker build -t $DOCKER_ID/atomic-coconut-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/atomic-coconut-client
  - docker push $DOCKER_ID/atomic-coconut-nginx
  - docker push $DOCKER_ID/atomic-coconut-server
