version: 0.2

env:
  parameter-store:
    DOCKER_ID: "/maxipaolucci/dockerID"
    DOCKER_PASSWORD: "/maxipaolucci/dockerPassword"

phases: 
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # - printenv
      - echo "installing something"
  pre_build:
    commands: 
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - echo $CURRENT_BRANCH
      - ./manage_images.sh
  post_build:
    commands:
      - echo "we are in the post build phase"
      # we don't need this one
      - rm docker-compose.yml
      # we need this one to be archived
      - mv docker-compose-beanstalk.yml docker-compose.yml

artifacts:
  files:
    # archive the only file necessary for elastikbeanstalk to redeploy the new docker images pushed
    - "docker-compose.yml"
    - ".platform/hooks/postdeploy/01-setup-cloudwatch-agent.sh"
  discard-paths: no # to keep directory structure
  name: atomiCoconut-build-artifact # this name seems to be completely ignored when codepipeline orchastrates this build
