version: 0.2

env:
  variables:
  parameter-store:
    DOCKER_ID: "/maxipaolucci/dockerID"
    DOCKER_PASSWORD: "/maxipaolucci/dockerPassword"

phases: 
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing something"
  pre_build:
    commands: 
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - ls -lh
      - echo $DOCKER_PASSWORD
      - echo $DOCKER_ID
      - CURRENT_BRANCH=$(basename $CODEBUILD_WEBHOOK_TRIGGER)
      - ./manage_images2.sh
  post_build:
    commands:
      - echo "we are in the post build phase"
