version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}

  acserver:
    # env_file:
    #   - variables.env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # ports: 
    #   - "7777:7777"
    volumes:
      - /app/node_modules
      - ./server:/app
    command: ["npm", "run", "dev"]

  acclient:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    # ports: 
    #   - "4200:4200"
    volumes:
      - /app/node_modules
      - ./client:/app
    command: ["npm", "start"]
  
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
        - "2222:80"