version: '3'
services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
    - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}

  acserver:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # ports: 
    #   - "7777:7777"
    environment:
      NODE_ENV: ${ENV}
      DATABASE: ${DATABASE}
      DATABASE_TEST: ${DATABASE_TEST} # required to run data-handler.js against test env
      DATABASE_PROD: ${DATABASE_PROD} # required to run data-handler.js against prod env
      MAIL_TRAP_USER: ${MAIL_TRAP_USER}
      MAIL_TRAP_PASS: ${MAIL_TRAP_PASS}
      MAIL_TRAP_HOST: ${MAIL_TRAP_HOST}
      MAIL_TRAP_PORT: ${MAIL_TRAP_PORT}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      PORT: ${PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_KEY: ${SESSION_KEY}
      SESSION_DURATION_SECONDS: ${SESSION_DURATION_SECONDS}
      CURRENCYLAYER_KEY: ${CURRENCYLAYER_KEY}
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_KEY: ${PUSHER_KEY}
      PUSHER_SECRET: ${PUSHER_SECRET}
      PUSHER_CLUSTER: ${PUSHER_CLUSTER}
      MAPS_API_KEY: ${MAPS_API_KEY}
      AWS_XRAY_CONTEXT_MISSING: ${AWS_XRAY_CONTEXT_MISSING}
    volumes:
    - /app/node_modules
    - ./server:/app
    - ./elk/logstash/logs:/app/logs # make logs files accessible by logstash
    command: ["npm", "run", "dev"]

  acclient:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile.dev.pwa
    # ports: 
    #   - "4200:4200"
    volumes:
    - /app/node_modules
    - ./client:/app
    command: ["npm", "start"]
  
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
    - "2222:80"
    volumes:
    # make logs files accessible by logstash
    - ./elk/logstash/logs:/var/log/nginx
  
  certbot:
    image: certbot/certbot
    volumes:
    - ./nginx/certbot/conf:/etc/letsencrypt
    - ./nginx/certbot/www:/var/www/certbot

  xraydaemon:
    # image: "amazon/aws-xray-daemon"
    build:
      context: ./xray
    ports:
    - "2000:2000"
    volumes: 
    - ~/.aws/:/root/.aws/:ro
    environment:
    - AWS_REGION=ap-southeast-2
    # mem_limit: 256m
    entrypoint: ["/xray", "-o", "-t", "0.0.0.0:2000", "-b", "0.0.0.0:2000"]
