# FROM node:14.15-alpine
FROM node:14-stretch-slim

# RUN apk update && apk add busybox-extras curl
RUN apt-get update && apt-get install -y curl unzip sudo
# install aws cli v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip -q awscliv2.zip
RUN sudo ./aws/install
RUN rm awscliv2.zip


RUN node -v && npm -v && aws --version

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .
