version: '3'
services:
  awscli:
    build:
      context: .
    restart: always
    env_file:
    - .env
    volumes: 
    - ~/.aws:/root/.aws:ro # for aws credentials
    - ../elk/logs/server:/aws/s3-logs/server:rw # make server log files imported from S3 accessible to filebeat
    - ../elk/logs/nginx:/aws/s3-logs/nginx:rw # make nginx log files imported from S3 accessible to filebeat
