# The other one in client folder is just for serving the frontend assets
# This one one in the nginx folder is for routing between the client and the server
FROM nginx

RUN apt update && apt install -y telnet curl iputils-ping traceroute htop net-tools vim

COPY ./testing.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443