FROM nginx

RUN apt update && apt install -y telnet curl iputils-ping traceroute htop net-tools vim logrotate

COPY ./default.conf /etc/nginx/conf.d/default.conf

# remove symlinks for logs
RUN unlink /var/log/nginx/access.log && unlink /var/log/nginx/error.log

EXPOSE 80