FROM docker.elastic.co/beats/filebeat:7.12.1
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN yum install -y telnet
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
USER filebeat