version: '3'
services:
  
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
  #   ports:
  #   - 9200:9200
  #   - 9300:9300
  #   environment:
  #     discovery.type: single-node
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.13.1
  #   depends_on: 
  #   - elasticsearch
  #   ports:
  #   - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.1
    # depends_on: 
    # - elasticsearch
    ports:
    - 5044:5044
    volumes:
    - ./logstash:/usr/share/logstash/pipeline:ro
    env_file:
    - .env

  filebeat:
    depends_on: 
    - logstash
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    volumes:
    # make logs files accessible to filebeat
    - ./logs:/usr/share/filebeat/logs:ro
    - ./filebeat/data:/usr/share/filebeat/data:rw
    env_file:
    - .env